# Generated by Django 2.2.12 on 2020-05-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
    ]
